@host = https://localhost:7016

### Get products - first page (cursor pagination)
GET {{host}}/api/products?limit=5

### Get products - next page (paste the nextCursor from the previous response)
GET {{host}}/api/products?limit=5&cursor=MzIx

### Get one product
GET {{host}}/api/products/680

### Get products - n+1
GET {{host}}/api/products/n-plus-one?limit=5

### Get products - eager
GET {{host}}/api/products/eager?limit=5

### Create a product
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "Learning Widget",
  "productNumber": "LW-0001",
  "makeFlag": false,
  "finishedGoodsFlag": false,
  "color": "Black",
  "safetyStockLevel": 100,
  "reorderPoint": 75,
  "standardCost": 10.50,
  "listPrice": 24.99,
  "size": null,
  "weight": null,
  "daysToManufacture": 0,
  "productSubcategoryID": null,
  "productModelID": null,
  "sellStartDate": "2026-01-01T00:00:00"
}

### Update a product
PUT {{host}}/api/products/680
Content-Type: application/json

{
  "name": "Updated Widget",
  "productNumber": "LW-0001",
  "makeFlag": false,
  "finishedGoodsFlag": false,
  "color": "Red",
  "safetyStockLevel": 100,
  "reorderPoint": 75,
  "standardCost": 11.00,
  "listPrice": 29.99,
  "size": null,
  "weight": null,
  "daysToManufacture": 0,
  "productSubcategoryID": null,
  "productModelID": null,
  "sellStartDate": "2026-01-01T00:00:00",
  "sellEndDate": null,
  "discontinuedDate": null
}

### Delete a product
DELETE {{host}}/api/products/680
